export const CHARACTERS = {
  luciano: {
    id: 'luciano',
    name: '"Lucky" Luciano',
    emoji: '\u{1F9D9}\u200D\u2642\uFE0F',
    desc: 'Roulette Gun \u2014 RNG bullets with stacking buffs.',
    attackType: 'ranged',
    radius: 16,
    speed: 5,
    hp: 10,
    maxHp: 10,
    stats: { VIT: 10, PWR: 2, ARM: 0, SPD: 5, JCE: 0, LCK: 1 },
    suit: 'diamonds',
    activeName: 'Russian Roulette',
    activeDesc: 'Next shot GREEN, then 6 forced RED shots.',
    passiveDesc: 'Black hits stack +5% Crit. Red hits stack +10% SPD. 3 max each, reset after 6 shots.',
  },
  valerie: {
    id: 'valerie',
    name: 'Lady Val',
    emoji: '\u{1F478}',
    desc: 'Card Thrower \u2014 Piercing projectiles that hit multiple enemies.',
    attackType: 'ranged',
    radius: 16,
    speed: 5.5,
    hp: 8,
    maxHp: 8,
    stats: { VIT: 8, PWR: 3, ARM: 0, SPD: 6, JCE: 0, LCK: 2 },
    suit: 'spades',
    activeName: 'Ante Up',
    activeDesc: 'Gravity trap pulls + damages enemies in 150px for 3s.',
    passiveDesc: 'Every 5th throw is a Joker dealing +2 bonus damage.',
  },
  buster: {
    id: 'buster',
    name: '"Buster" Malone',
    emoji: '\u{1F44A}',
    desc: 'Slot Fist \u2014 Melee slot-machine brawler.',
    attackType: 'melee',
    meleeRange: 60,
    radius: 20,
    speed: 4.5,
    hp: 14,
    maxHp: 14,
    stats: { VIT: 14, PWR: 1, ARM: 2, SPD: 4, JCE: 0, LCK: 1 },
    suit: 'clubs',
    activeName: 'Max Bet',
    activeDesc: 'Double attack speed + boosted slot odds for 6s.',
    passiveDesc: 'Cherries=Fire, Diamonds=Armor, 777=Gold blast, Bust=-1 HP.',
  },
  silas: {
    id: 'silas',
    name: 'Silas Vance',
    emoji: '\u{1F9D1}\u200D\u{1F3A8}',
    desc: 'Whip Specialist \u2014 Medium-range melee with 2d6 dice.',
    attackType: 'melee',
    meleeRange: 150,
    radius: 16,
    speed: 5,
    hp: 10,
    maxHp: 10,
    stats: { VIT: 10, PWR: 2, ARM: 0, SPD: 5, JCE: 0, LCK: 3 },
    suit: null,
    activeName: 'Loaded Dice',
    activeDesc: 'Force Snake Eyes (2), take 1 HP, double speed for 5s.',
    passiveDesc: '2d6: 7/11=knockback, 2=self-dmg+speed, 3-6=stack +20% dmg buff.',
  },
  roxanne: {
    id: 'roxanne',
    name: 'Madam Roxanne',
    emoji: '\u{1F9D9}\u200D\u2640\uFE0F',
    desc: 'Shield Tank \u2014 Blackjack-stacking melee tank.',
    attackType: 'melee',
    meleeRange: 60,
    radius: 22,
    speed: 4,
    hp: 16,
    maxHp: 16,
    stats: { VIT: 16, PWR: 1, ARM: 3, SPD: 4, JCE: 0, LCK: 1 },
    suit: 'hearts',
    activeName: 'Double Down',
    activeDesc: 'Double blackjack gain for 4s. At 21 = AOE stun blast.',
    passiveDesc: 'Enemy hits stack blackjack. At 21 = AOE blast. Bust (over 21) = 3s silence.',
  },
};
